# Generated by Django 3.1.2 on 2021-04-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_report_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
