# Generated by Django 3.1.2 on 2021-04-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='title',
        ),
    ]
